### ISSUE TITLE
[Bug] Unable to install on standard user account.

### ISSUE THREAD

**Issue by oneironaut2209** [LSPosed/MagiskOnWSALocal#276]
### Steps to reproduce/复现步骤

1.  Login standard user account.
2.  Run Run.bat
3.  Grant Administrative permissions.
4.  It will throw an error

### Expected behaviour/预期行为

Should open WSA app

### Actual behaviour/实际行为

Gives error. See screenshot below. It works fine on admin logged account.

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

78a408de0ce9d576323cd9c8e9c8e8d72b59cc2d

### Linux distribution info/Linux 发行版信息

Ubuntu 22.04.1 LTS

### Windows version/Windows 版本

22000.1281

### Build Parameters/构建参数

INFO: Architecture: x64
INFO: Release Type: retail
INFO: Magisk Version: stable
INFO: GApps Brand: MindTheGapps
INFO: GApps Variant: pico
INFO: Root Solution: magisk
Build: RELEASE_TYPE=Retail

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

![image](https://user-images.githubusercontent.com/63645932/206087266-ecd71d3e-ddca-4c47-92c5-f9d381e22e28.png)

**Comment by Howard20181** [comment]
Please install in admin accout

**Comment by rom4ster** [comment]
Why is this not planned? Installing as an admin makes it so that it is impossible to use this without logging in as an administrator.

I cannot run any WSA through an elevated shell as it requires an interactive session

 Running an admin shell will not work. It is good security practice and frankly a normal part of windows to use a non admin account for daily driving. Please resolve this issue. I can install WSA through windows store on my non admin account so the issue is in this installer or app package. 
 
 Discriminating against users with security practices is never a good look for any piece of software so please re open this and fix

**Comment by zamarax** [comment]
Honestly, I have to agree here as well, it's terribly bad practice.

__
Regards, Corey Zamara

**Comment by Howard20181** [comment]
There is no possibility to install without administrator privileges
1. If you install the unpacked MSIX package, you must install it in developer mode, which requires that it must be done with administrator privileges
2. If you want to install packaged WSA, which must be unmodified, then it is not possible to integrate Magisk.
3. if you want to repackage after integrating Magisk, you must sign the installation package, applying for a valid signature requires a paid application as a company, if not applying for a signature, self-signed installation packages using development signatures require sideloading in developer mode, which goes back to point 1


Translated with www.DeepL.com/Translator (free version)

**Comment by rom4ster** [comment]
YOu should make a signed install option, since its all unpacked anyways, and let the user provide the certificate. That is still better practice than just disabling the option all together.
