### ISSUE TITLE
[Bug] Most recent version of WSA is not downloading?

### ISSUE THREAD

**Issue by clubtech** [LSPosed/MagiskOnWSALocal#279]
### Steps to reproduce/复现步骤

1. Run run.sh
2. Choose insider_fast channel

### Expected behaviour/预期行为

The most recent version is expected to download (2211.40000.7.0) however instead I am getting version 2210.40000.7.0 which is the version before the last version

### Actual behaviour/实际行为

The script does not download the latest version no matter the channel I am selecting

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

Not sure how to display SHA commit, downloaded lates from today

### Linux distribution info/Linux 发行版信息

Ubuntu on WSL

### Windows version/Windows 版本

10.0.2263.1028

### Build Parameters/构建参数

COMMAND_LINE=--arch x64 --release-type WIF --magisk-ver stable --gapps-brand OpenGApps --gapps-variant pico  --root-sol none     --compress-format
INFO: Architecture: x64
INFO: Release Type: WIF
INFO: Magisk Version: stable
INFO: GApps Brand: OpenGApps
INFO: GApps Variant: pico
INFO: Root Solution: none
Build: RELEASE_TYPE=Insider Fast

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<img width="793" alt="Screenshot 2022-12-07 221400" src="https://user-images.githubusercontent.com/15256218/206371611-a9a7180a-c3fd-445a-aadd-6a9fb56beee9.png">

**Comment by Howard20181** [comment]
This is the latest version returned from the API and we cannot fix

**Comment by flobo09** [comment]
This is because the WSA beta is no longer linked to the windows insider program. You have to join the WSA preview program (in the WSA configuration / settings app) and THEN you will find the update in the Windows Store. 

I edited the script to replace the download by the A13 package i manually downloaded and it's working perfectly with Android 13. 

@Howard20181 : Could be an idea of a future improvement to manually allow user to choose a locally downloaded package without having to edit the script since i don't think you will be able to get the package with the news system.

**Comment by Howard20181** [comment]
@flobo09 We already have the skip download WSA flag

**Comment by znoow** [comment]
@Howard20181 How can we use the skip download WSA flag? I’m trying to create a 2211 build with Magisk, but have no idea how to do it. I signed up a few days ago for the WSA preview program, but I don’t receive any email confirmation for the WSA preview program. :/

Can we somehow tell MagiskonWSALocal to use this archive -> https://github.com/Howard20181/WSA-bundle/releases/tag/v2211.40000.10.0 ??? 🤔

**Comment by clubtech** [comment]
@znoow you can use the flag  --skip-download-wsa when running build.sh but I am not sure how you can use the archive you posted. I would also like to know how to use that archive.
@Howard20181 can you assist?

**Comment by flobo09** [comment]
I did it in the dumbest way possible because i couldn't be bothered to take time with that. 

I added a pause after the extracting of the package is done in the script and i manually replaced the content with the content of the new package instead.  

It works perfectly.

**Comment by Howard20181** [comment]
1. Rename `MicrosoftCorporationII.WindowsSubsystemForAndroid_2211.40000.10.0_neutral___8wekyb3d8bbwe.Msixbundle` to `wsa-WIF.zip` then put it into download folder
1. Run `build.sh --release-type WIF --skip-download-wsa`

**Comment by clubtech** [comment]
Thank you. This worked!

**Comment by znoow** [comment]
> 1. Rename `MicrosoftCorporationII.WindowsSubsystemForAndroid_2211.40000.10.0_neutral___8wekyb3d8bbwe.Msixbundle` to `wsa-WIF.zip` then put it into download folder
> 2. Run `build.sh --release-type WIF --skip-download-wsa`

@Howard20181 Looks like there's a problem:

```
Shrink images done

Remove signature and add scripts
cp: cannot stat '../download/Microsoft.VCLibs.x64.14.00.Desktop.appx': No such file or directory
cp: cannot stat '../download/Microsoft.UI.Xaml_x64.appx': No such file or directory
Build: an error has occurred, exit
Cleanup Work Directory
umount: /tmp/wsa-build-a9sTPU7AwF_/system: not mounted.
Cleanup Download Directory
```

Perhaps `Microsoft.VCLibs.x64.14.00.Desktop.appx` and `Microsoft.UI.Xaml_x64.appx` are missing now given that `--skip-download-wsa` was used?! Or because I never downloaded them before? So this could happen to a "clean machine" that never built WSA images before?! 🤔

**Comment by clubtech** [comment]
Microsoft.VCLibs.x64.14.00.Desktop.appx and Microsoft.UI.Xaml_x64.appx are downloaded when you run the script **without** the --skip-download-wsa. Keep a copy of these two files, place them again in the download folder along with the 2211 WSA file and run the script with the --skip-download-wsa flag

**Comment by shrublet** [comment]
I followed the steps detailed above, but for some reason, 2211 refuses to boot up for me. 2210 or 2209 work fine, but 2211 will just get stuck starting the subsystem and then close. Ran `./build.sh --arch x64 --release-type WIF --magisk-ver stable --gapps-brand OpenGApps --gapps-variant pico --remove-amazon --root-sol magisk --compress --skip-download-wsa --compress-format 7z` and this works fine for 2210, but again, not 2211. 2211 did work once for me, but I had to re-install because I accidentally forgot to remove Amazon store. Since then, it's been failing to run. This is of course after uninstalling multiple times, not trying to upgrade. If anybody has any advice, I'd appreciate it.

**Comment by Howard20181** [comment]
> I followed the steps detailed above, but for some reason, 2211 refuses to boot up for me. 2210 or 2209 work fine, but 2211 will just get stuck starting the subsystem and then close. Ran `./build.sh --arch x64 --release-type WIF --magisk-ver stable --gapps-brand OpenGApps --gapps-variant pico --remove-amazon --root-sol magisk --compress --skip-download-wsa --compress-format 7z` and this works fine for 2210, but again, not 2211. 2211 did work once for me, but I had to re-install because I accidentally forgot to remove Amazon store. Since then, it's been failing to run. This is of course after uninstalling multiple times, not trying to upgrade. If anybody has any advice, I'd appreciate it.

Don't use OpenGapps as it only build for Android 11
