### ISSUE TITLE
[Bug] 不完整的OpenGApps

### ISSUE THREAD

**Issue by Doddddd** [LSPosed/MagiskOnWSALocal#352]
### Steps to reproduce/复现步骤

./run.sh

### Expected behaviour/预期行为

完整的OpenGApps

### Actual behaviour/实际行为

<img width="349" alt="{210CD298-AFC9-4F8B-90AE-0D107B4EE18F}" src="https://user-images.githubusercontent.com/88972478/212537226-efb2c670-e15d-41a9-8e41-3e2e5e22bd1a.png">

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

dc7083c

### Linux distribution info/Linux 发行版信息

Ubuntu 22.10

### Windows version/Windows 版本

10.0.22621.1105

### Build Parameters/构建参数

COMMAND_LINE=--arch x64 --release-type WIF --magisk-ver stable --gapps-brand OpenGApps --gapps-variant pico --remove-amazon --root-sol magisk --compress    --compress-format 7z
INFO: Architecture: x64
INFO: Release Type: WIF
INFO: Magisk Version: stable
INFO: GApps Brand: OpenGApps
INFO: GApps Variant: pico
INFO: Root Solution: magisk
INFO: Compress Format: 7z
Build: RELEASE_TYPE=Insider Fast

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

[20230115105127.log](https://github.com/LSPosed/MagiskOnWSALocal/files/10419987/20230115105127.log)

**Comment by Howard20181** [comment]
在OpenGapps发布新版之前不修
现在只能用Android 11的
现在除了pico的其他全部bootloop


Best regards

,
Howard
________________________________
From: Doddddd ***@***.***>
Sent: Sunday, January 15, 2023 7:11:44 PM
To: LSPosed/MagiskOnWSALocal ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [LSPosed/MagiskOnWSALocal] [Bug] 不完整的OpenGApps (Issue #352)


Steps to reproduce/复现步骤

./run.sh

Expected behaviour/预期行为

完整的OpenGApps

Actual behaviour/实际行为

[{210CD298-AFC9-4F8B-90AE-0D107B4EE18F}]<https://user-images.githubusercontent.com/88972478/212537226-efb2c670-e15d-41a9-8e41-3e2e5e22bd1a.png>

MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

dc7083c<https://github.com/LSPosed/MagiskOnWSALocal/commit/dc7083ccface4eac389bbeff4b3aad049116c888>

Linux distribution info/Linux 发行版信息

Ubuntu 22.10

Windows version/Windows 版本

10.0.22621.1105

Build Parameters/构建参数

COMMAND_LINE=--arch x64 --release-type WIF --magisk-ver stable --gapps-brand OpenGApps --gapps-variant pico --remove-amazon --root-sol magisk --compress --compress-format 7z
INFO: Architecture: x64
INFO: Release Type: WIF
INFO: Magisk Version: stable
INFO: GApps Brand: OpenGApps
INFO: GApps Variant: pico
INFO: Root Solution: magisk
INFO: Compress Format: 7z
Build: RELEASE_TYPE=Insider Fast

Version requirement/版本要求

  *    I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

Logs/日志

20230115105127.log<https://github.com/LSPosed/MagiskOnWSALocal/files/10419987/20230115105127.log>

―
