### ISSUE TITLE
[Bug] "WsaClient.exe" crashes.

### ISSUE THREAD

**Issue by creeper-0910** [LSPosed/MagiskOnWSALocal#371]
### Steps to reproduce/复现步骤

1. Using Ubuntu 20.04, build MagiskOnWSALocal (b84eb4063fd9744adee31c049a20e15371fac432).
The commands used are as follows:
```
git clone https://github.com/LSPosed/MagiskOnWSALocal.git
cd MagiskOnWSALocal/scripts/
run.sh
(*)x64
(*)retail
(*)stable
<Yes>
(*)OpenGApps
<No>
(*)none
<Yes>
(*)7z
```
3. Execute "run.bat".

### Expected behaviour/预期行为

WSA starts up.

### Actual behaviour/实际行为

 WsaClinet.exe crashes during startup.

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

b84eb4063fd9744adee31c049a20e15371fac432

### Linux distribution info/Linux 发行版信息

Ubuntu20.04(WSL)

### Windows version/Windows 版本

10.0.22000.1455

### Build Parameters/构建参数

COMMAND_LINE=--arch x64 --release-type retail --magisk-ver stable --gapps-brand OpenGApps --gapps-variant pico --remove-amazon --root-sol none --compress    --compress-format 7z
INFO: Architecture: x64
INFO: Release Type: retail
INFO: Magisk Version: stable
INFO: GApps Brand: OpenGApps
INFO: GApps Variant: pico
INFO: Root Solution: none
INFO: Compress Format: 7z
Build: RELEASE_TYPE=Retail

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>

```
障害が発生しているアプリケーション名: WsaClient.exe、バージョン: 2211.40000.11.0、タイム スタンプ: 0x63b5f0cc
障害が発生しているモジュール名: WsaClient.exe、バージョン: 2211.40000.11.0、タイム スタンプ: 0x63b5f0cc
例外コード: 0xc0000409
障害オフセット: 0x000000000001d950
障害が発生しているプロセス ID: 0x3160
障害が発生しているアプリケーションの開始時刻: 0x01d9331518aa05c9
障害が発生しているアプリケーション パス: C:\Users\e12yu\Desktop\WSA_2211.40000.11.0_x64_Release-Nightly-OpenGApps-11.0-pico-RemovedAmazon\WsaClient\WsaClient.exe
障害が発生しているモジュール パス: C:\Users\e12yu\Desktop\WSA_2211.40000.11.0_x64_Release-Nightly-OpenGApps-11.0-pico-RemovedAmazon\WsaClient\WsaClient.exe
レポート ID: 350490b1-e0b2-47aa-a880-81ca40295b69
障害が発生しているパッケージの完全な名前: MicrosoftCorporationII.WindowsSubsystemForAndroid_2211.40000.11.0_x64__8wekyb3d8bbwe
障害が発生しているパッケージに関連するアプリケーション ID: App
```
</details>

**Comment by Howard20181** [comment]
Please check if official unmodified WSA work, consider report to Microsoft.


Best regards

,
Howard
________________________________
From: おのCreeeper ***@***.***>
Sent: Saturday, January 28, 2023 9:12:01 PM
To: LSPosed/MagiskOnWSALocal ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [LSPosed/MagiskOnWSALocal] [Bug] "WsaClient.exe" crashes. (Issue #371)


Steps to reproduce/复现步骤

  1.  Using Ubuntu 20.04, build MagiskOnWSALocal (b84eb40<https://github.com/LSPosed/MagiskOnWSALocal/commit/b84eb4063fd9744adee31c049a20e15371fac432>).
The commands used are as follows:

git clone https://github.com/LSPosed/MagiskOnWSALocal.git

cd MagiskOnWSALocal/scripts/

run.sh

(*)x64

(*)retail

(*)stable

<Yes>

(*)OpenGApps

<No>

(*)none

<Yes>

(*)7z



  1.  Execute "run.bat".

Expected behaviour/预期行为

WSA starts up.

Actual behaviour/实际行为

WsaClinet.exe crashes during startup.

MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

b84eb40<https://github.com/LSPosed/MagiskOnWSALocal/commit/b84eb4063fd9744adee31c049a20e15371fac432>

Linux distribution info/Linux 发行版信息

Ubuntu20.04(WSL)

Windows version/Windows 版本

10.0.22000.1455

Build Parameters/构建参数

COMMAND_LINE=--arch x64 --release-type retail --magisk-ver stable --gapps-brand OpenGApps --gapps-variant pico --remove-amazon --root-sol none --compress --compress-format 7z
INFO: Architecture: x64
INFO: Release Type: retail
INFO: Magisk Version: stable
INFO: GApps Brand: OpenGApps
INFO: GApps Variant: pico
INFO: Root Solution: none
INFO: Compress Format: 7z
Build: RELEASE_TYPE=Retail

Version requirement/版本要求

  *    I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

Logs/日志

障害がk生しているアプリケ`ション名: WsaClient.exe、バ`ジョン: 2211.40000.11.0、タイム スタンプ: 0x63b5f0cc

障害がk生しているモジュ`ル名: WsaClient.exe、バ`ジョン: 2211.40000.11.0、タイム スタンプ: 0x63b5f0cc

例外コ`ド: 0xc0000409

障害オフセット: 0x000000000001d950

障害がk生しているプロセス ID: 0x3160

障害がk生しているアプリケ`ションの_始r刻: 0x01d9331518aa05c9

障害がk生しているアプリケ`ション パス: C:\Users\e12yu\Desktop\WSA_2211.40000.11.0_x64_Release-Nightly-OpenGApps-11.0-pico-RemovedAmazon\WsaClient\WsaClient.exe

障害がk生しているモジュ`ル パス: C:\Users\e12yu\Desktop\WSA_2211.40000.11.0_x64_Release-Nightly-OpenGApps-11.0-pico-RemovedAmazon\WsaClient\WsaClient.exe

レポ`ト ID: 350490b1-e0b2-47aa-a880-81ca40295b69

障害がk生しているパッケ`ジの完全な名前: MicrosoftCorporationII.WindowsSubsystemForAndroid_2211.40000.11.0_x64__8wekyb3d8bbwe

障害がk生しているパッケ`ジにvBするアプリケ`ション ID: App



―

**Comment by creeper-0910** [comment]
I understand.
Appreciate your quick reply!

**Comment by creeper-0910** [comment]
It seems that if "OpenGApps" is selected, it fails to start.

**Comment by Howard20181** [comment]
OpenGapps hasn't been updated for a long time, now you can only use the one built for Android 11. Switch to MindtheGApps and you can use it normally.


Best regards

,
Howard
________________________________

**Comment by creeper-0910** [comment]
Maybe we should add this to the README (just in case).
