### ISSUE TITLE
建议每月发布一个release，而不是github actions

### ISSUE THREAD

**Issue by SekiBetu** [LSPosed/MagiskOnWSALocal#4]
建议每月发布一个release，而不是github actions，这样原仓库应该就没问题了

**Comment by Howard20181** [comment]
不知道会不会有版权问题
而且发布Release之后下载量大也不行，之前OpenGapps就迁移了

**Comment by SekiBetu** [comment]
那没办法了，把微软干趴下了属于是，要么release放在谷歌盘之类的地方吧，没有版权问题的吧，WSA内核是开源的吧

**Comment by Howard20181** [comment]
现在Github没有回应是什么原因禁用

**Comment by PeterNjeim** [comment]
I don't like it when copmanies don't specify what term of the ToS was violated, it's not transparent. But of course, we all know that the old repository abused GitHub Actions, and even I called you guys out on that, and released my own fork that used Releases instead of Actions (mainly because it's way faster (47x faster) and more reliable anyways). Unfortunately, since it was a fork, my repository got disabled as well. I am now in contact with GitHub to reinstate my repository. If they do, then I will report back here and confirm that it wasn't a copyright issue. If they deny my request, then we can safely say that it would be a copyright issue and that this local method is the correct way forward.

**Comment by PeterNjeim** [comment]
@Howard20181
They replied to me, it is confirmed an Actions issue. If you use Releases like I did I'm sure it wouldn't violate their policies.

![image](https://user-images.githubusercontent.com/26418974/186056627-866dfa33-3c2d-4baa-8d4c-2a1fb5856f89.png)

**Comment by PeterNjeim** [comment]
@Howard20181 My repository just got banned just like your old one lol. I'm contacting them right now to see if Releases are also a problem, or if it's a copyright issue. Hopefully this repository doesn't get banned too!
