### ISSUE TITLE
[Bug] Failed to download WSA

### ISSUE THREAD

**Issue by AndersonCV** [LSPosed/MagiskOnWSALocal#435]
### Steps to reproduce/复现步骤

1. Start ./run.sh
2. Build with any parameters

### Expected behaviour/预期行为

It should start downloading all the WSA files

### Actual behaviour/实际行为

Generate Download Links
Traceback (most recent call last):
  File "/home/msi/MagiskOnWSALocal/scripts/generateWSALinks.py", line 31, in <module>
    from requests import Session
ModuleNotFoundError: No module named 'requests'
Build: an error has occurred, exit

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

8e3eef35a9f8ded7892477ab6f8cfea08af85387

### Linux distribution info/Linux 发行版信息

Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy

### Windows version/Windows 版本

25314.1010

### Build Parameters/构建参数

COMMAND_LINE=--arch x64 --release-type WIF --magisk-ver canary --gapps-brand MindTheGapps --gapps-variant pico --remove-amazon --root-sol magisk     --compress-format
INFO: Architecture: x64
INFO: Release Type: WIF
INFO: Magisk Version: canary
INFO: GApps Brand: MindTheGapps
INFO: GApps Variant: pico
INFO: Root Solution: magisk
Build: RELEASE_TYPE=Insider Fast

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

![Screenshot 2023-03-21 124936](https://user-images.githubusercontent.com/85256569/226697810-8c94ced0-70aa-4404-8f7c-7fd899d17130.png)

**Comment by Howard20181** [comment]
Run `scripts/install_deps.sh`


Best regards,

Howard
________________________________
From: Anderson ***@***.***>
Sent: Wednesday, March 22, 2023 1:50:53 AM
To: LSPosed/MagiskOnWSALocal ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [LSPosed/MagiskOnWSALocal] [Bug] Failed to download WSA (Issue #435)


Steps to reproduce/复现步骤

  1.  Start ./run.sh
  2.  Build with any parameters

Expected behaviour/预期行为

It should start downloading all the WSA files

Actual behaviour/实际行为

Generate Download Links
Traceback (most recent call last):
File "/home/msi/MagiskOnWSALocal/scripts/generateWSALinks.py", line 31, in
from requests import Session
ModuleNotFoundError: No module named 'requests'
Build: an error has occurred, exit

MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

8e3eef3<https://github.com/LSPosed/MagiskOnWSALocal/commit/8e3eef35a9f8ded7892477ab6f8cfea08af85387>

Linux distribution info/Linux 发行版信息

Distributor ID: Ubuntu
Description: Ubuntu 22.04.1 LTS
Release: 22.04
Codename: jammy

Windows version/Windows 版本

25314.1010

Build Parameters/构建参数

COMMAND_LINE=--arch x64 --release-type WIF --magisk-ver canary --gapps-brand MindTheGapps --gapps-variant pico --remove-amazon --root-sol magisk --compress-format
INFO: Architecture: x64
INFO: Release Type: WIF
INFO: Magisk Version: canary
INFO: GApps Brand: MindTheGapps
INFO: GApps Variant: pico
INFO: Root Solution: magisk
Build: RELEASE_TYPE=Insider Fast

Version requirement/版本要求

  *    I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

Logs/日志

[Screenshot 2023-03-21 124936]<https://user-images.githubusercontent.com/85256569/226697810-8c94ced0-70aa-4404-8f7c-7fd899d17130.png>

―

**Comment by AndersonCV** [comment]
I had to add universe, but yes, that was the solution, thanks
