### ISSUE TITLE
[Feature Request] Add releaseflow

### ISSUE THREAD

**Issue by HidemaruOwO** [LSPosed/MagiskOnWSALocal#682]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

No

### Describe the solution you'd like/描述你想要的解决方案

Please distribute the results in a GitHub release.
This can be automated with GitHub Actions.

**Comment by HidemaruOwO** [comment]
Currently working on it.
We have successfully built and released in the workflow, but have not tried to see if the built artifacts work on Windows, so we will try later.
https://github.com/HidemaruOwO/MagiskOnWSALocal

Download
https://github.com/HidemaruOwO/MagiskOnWSALocal/releases

**Comment by HidemaruOwO** [comment]
I also merge the content of this PR.
On merge,Committed under the name YT-Advanced.
https://github.com/LSPosed/MagiskOnWSALocal/pull/620

**Comment by HidemaruOwO** [comment]
We will send out a PR as soon as we confirm that it works.

**Comment by s1204IT** [comment]
"[**MagiskOnWSA**](https://github.com/LSPosed/MagiskOnWSA)" was disabled because building of WSA using GitHub Actions.  
It has been testified to in the past by Mr. Howard of LSPosed.

**All work done in local host.** (https://github.com/LSPosed/MagiskOnWSALocal/commit/555c643)
Since this commit, the repository, renamed "**MagiskOnWSA\*\*Local\*\***", has been developed with the assumption that it will be built with WSL.

**Comment by HidemaruOwO** [comment]
I understrand
